<x-layout></x-layout>
<x-parentnav :students="$students">
    <div class="max-w-sm w-full bg-white rounded-lg shadow dark:bg-gray-800 p-4 md:p-6">
        <div class="flex justify-between mb-5">
            <div class="grid gap-4 grid-cols-2">
                <div>
                    <h5 class="inline-flex items-center text-gray-500 dark:text-gray-400 leading-none font-normal mb-2">Clicks
                        <svg data-popover-target="clicks-info" data-popover-placement="bottom" class="w-3 h-3 text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                        </svg>
                        <div data-popover id="clicks-info" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                            <div class="p-3 space-y-2">
                                <h3 class="font-semibold text-gray-900 dark:text-white">Clicks growth - Incremental</h3>
                                <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
                                <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                                <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
                                <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                                    </svg></a>
                            </div>
                            <div data-popper-arrow></div>
                        </div>
                    </h5>
                    <p id="clicks-value" class="text-gray-900 dark:text-white text-2xl leading-none font-bold">Loading...</p>
                </div>
                <div>
                    <h5 class="inline-flex items-center text-gray-500 dark:text-gray-400 leading-none font-normal mb-2">CPC
                        <svg data-popover-target="cpc-info" data-popover-placement="bottom" class="w-3 h-3 text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 1 1 0 2Z"/>
                        </svg>
                        <div data-popover id="cpc-info" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                            <div class="p-3 space-y-2">
                                <h3 class="font-semibold text-gray-900 dark:text-white">CPC growth - Incremental</h3>
                                <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
                                <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                                <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
                                <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                                    </svg></a>
                            </div>
                            <div data-popper-arrow></div>
                        </div>
                    </h5>
                    <p id="cpc-value" class="text-gray-900 dark:text-white text-2xl leading-none font-bold">Loading...</p>
                </div>
            </div>
            <div>
                <button id="dropdownDefaultButton"
                        data-dropdown-toggle="lastDaysdropdown"
                        data-dropdown-placement="bottom" type="button" class="px-3 py-2 inline-flex items-center text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Last week <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                    </svg></button>
                <div id="lastDaysdropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Yesterday</a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Today</a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 7 days</a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 30 days</a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last month</a>
                        </li>
                        <li>
                            <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last year</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="p-2 bg-gray-100 rounded-lg dark:bg-gray-700">
            <canvas id="performanceChart" width="400" height="300"></canvas>
        </div>
        <div class="pt-5">
            <a href="#" class="text-blue-600 dark:text-blue-500 hover:underline font-medium inline-flex items-center">View full report
                <svg class="ms-1 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                </svg></a>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Fetch clicks and CPC data
            axios.get('/api/clicks')
                .then(function (response) {
                    document.getElementById('clicks-value').innerText = response.data.clicks;
                })
                .catch(function (error) {
                    console.error('Error fetching clicks:', error);
                    document.getElementById('clicks-value').innerText = 'Error';
                });

            axios.get('/api/cpc')
                .then(function (response) {
                    document.getElementById('cpc-value').innerText = response.data.cpc;
                })
                .catch(function (error) {
                    console.error('Error fetching CPC:', error);
                    document.getElementById('cpc-value').innerText = 'Error';
                });

            // Fetch and render student performance data
            axios.get('/api/students/1/performance')
                .then(function (response) {
                    const marks = response.data.marks;
                    const labels = marks.map(mark => mark.exam_name);
                    const data = marks.map(mark => mark.performance);

                    const ctx = document.getElementById('performanceChart').getContext('2d');
                    new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: labels,
                            datasets: [{
                                label: 'Performance',
                                data: data,
                                borderColor: 'blue',
                                backgroundColor: 'lightblue',
                            }]
                        },
                        options: {
                            responsive: true,
                            plugins: {
                                legend: {
                                    position: 'top',
                                },
                            },
                        }
                    });
                })
                .catch(function (error) {
                    console.error('Error fetching student performance:', error);
                });
        });
    </script>
</x-parentnav>

<x-layout>
        <div class="container mx-auto p-6 bg-white shadow-md">
            <div class="flex">
                <!-- Sidebar -->
                <div class="w-1/4 bg-gray-800 text-white h-screen">
                    <div class="p-4">
                        <h2 class="text-2xl font-bold mb-4">Parent Dashboard</h2>
                        <ul class="space-y-4">
                            <li>
                                <a href="#overview" class="block p-2 rounded hover:bg-gray-700">Overview</a>
                            </li>
                            <li>
                                <a href="#performance" class="block p-2 rounded hover:bg-gray-700">Student Performance</a>
                            </li>
                            <li>
                                <a href="#attendance" class="block p-2 rounded hover:bg-gray-700">Attendance Records</a>
                            </li>
                            <li>
                                <a href="#activities" class="block p-2 rounded hover:bg-gray-700">School Activities</a>
                            </li>
                            <li>
                                <a href="/chat" class="block p-2 rounded hover:bg-gray-700">Inbox</a>
                            </li>
                            <li>
                                <a href="#feedback" class="block p-2 rounded hover:bg-gray-700">Feedback and Support</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Main Content -->
                <div class="w-3/4 p-6">
                    <!-- Overview Section -->
                    <section id="overview" class="mb-6">
                        <h2 class="text-xl font-semibold mb-4">Overview</h2>
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                            <div class="bg-gray-100 p-4 rounded-lg">
                                <h3 class="text-lg font-medium">Overall Performance</h3>
                                <p>Average Grade: A</p>
                                <p>Attendance: 95%</p>
                            </div>
                            <div class="bg-gray-100 p-4 rounded-lg">
                                <h3 class="text-lg font-medium">Recent Grades</h3>
                                <ul>
                                    <li>Math: A</li>
                                    <li>Science: B+</li>
                                    <li>English: A-</li>
                                </ul>
                            </div>
                            <div class="bg-gray-100 p-4 rounded-lg">
                                <h3 class="text-lg font-medium">Upcoming Events</h3>
                                <ul>
                                    <li>Parent-Teacher Meeting: June 15</li>
                                    <li>School Trip: July 20</li>
                                </ul>
                            </div>
                        </div>
                    </section>

                    <!-- Student Performance Section -->
                    <section id="performance" class="mb-6">
                        <h2 class="text-xl font-semibold mb-4">Student Performance</h2>
                        <div class="bg-gray-100 p-4 rounded-lg">
                            <h3 class="text-lg font-medium">Subject-wise Performance</h3>
                            <p>Details of grades and assignments.</p>
                        </div>
                    </section>

                    <!-- Attendance Section -->
                    <section id="attendance" class="mb-6">
                        <h2 class="text-xl font-semibold mb-4">Attendance Records</h2>
                        <div class="bg-gray-100 p-4 rounded-lg">
                            <h3 class="text-lg font-medium">Attendance Logs</h3>
                            <p>Daily, weekly, and monthly attendance records.</p>
                        </div>
                    </section>

                    <!-- School Activities Section -->
                    <section id="activities" class="mb-6">
                        <h2 class="text-xl font-semibold mb-4">School Activities</h2>
                        <div class="bg-gray-100 p-4 rounded-lg">
                            <h3 class="text-lg font-medium">Event Calendar</h3>
                            <p>Calendar of upcoming events with options to RSVP.</p>
                        </div>
                    </section>

                    <!-- Communication Tools Section -->
                    <section id="communication" class="mb-6">
                        <h2 class="text-xl font-semibold mb-4">Communication Tools</h2>
                        <div class="bg-gray-100 p-4 rounded-lg">
                            <h3 class="text-lg font-medium">Messages</h3>
                            <p>Messaging system to communicate with teachers.</p>
                        </div>
                    </section>

                    <!-- Feedback and Support Section -->
                    <section id="feedback" class="mb-6">
                        <h2 class="text-xl font-semibold mb-4">Feedback and Support</h2>
                        <div class="bg-gray-100 p-4 rounded-lg">
                            <h3 class="text-lg font-medium">Provide Feedback</h3>
                            <p>Option to provide feedback and access support resources.</p>
                        </div>
                    </section>
                </div>
            </div>
        </div>


</x-layout>


